// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgKxjrV9ziOmLlAmPSKL6xceERMNYDEn8',
    appId: '1:457350094201:web:3a0364739b2aac66f9e3a8',
    messagingSenderId: '457350094201',
    projectId: 'cosmicbeacon',
    authDomain: 'cosmicbeacon.firebaseapp.com',
    databaseURL: 'https://cosmicbeacon-default-rtdb.firebaseio.com',
    storageBucket: 'cosmicbeacon.appspot.com',
    measurementId: 'G-J9YSLRVP0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP5BS_h5-L559Pw_dioh-h046TgFFkVWo',
    appId: '1:457350094201:android:da511feeddd079d8f9e3a8',
    messagingSenderId: '457350094201',
    projectId: 'cosmicbeacon',
    databaseURL: 'https://cosmicbeacon-default-rtdb.firebaseio.com',
    storageBucket: 'cosmicbeacon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKCQT0Kgg1H6uiXIhyHoGRjk7RL0FAA_A',
    appId: '1:457350094201:ios:dc8fcbef7feead8ff9e3a8',
    messagingSenderId: '457350094201',
    projectId: 'cosmicbeacon',
    databaseURL: 'https://cosmicbeacon-default-rtdb.firebaseio.com',
    storageBucket: 'cosmicbeacon.appspot.com',
    androidClientId: '457350094201-hhl86ql1i1j4qf6plhuuvgv02ao5d341.apps.googleusercontent.com',
    iosClientId: '457350094201-8sb3vclq8g2ejemtftg4o0lj39gfj0md.apps.googleusercontent.com',
    iosBundleId: 'tech.fortmea.cosmicbeacon.cosmicBeacon',
  );

}